spring:
  profiles:
    active: prod
  devtools:
    restart:
      enabled: true  #设置开启热部署
  freemarker:
    cache: false    #页面不加载缓存，修改即时生效
  application:
    name: sso-server
  mvc:
    static-path-pattern: /sso/** #静态资源访问路径
  thymeleaf:
    prefix: classpath:/template/
    suffix: .html
    content-type: text/html
  http:
    encoding:
      force: true
mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: cn.ct.ks


